version: 2
jobs:
  build:
    docker:
      - image: microflash/node:14-buster
    environment:
      - GIT_LFS_SKIP_SMUDGE: 1
    working_directory: ~/repo
    steps:
      - checkout
      - run: git lfs ls-files -l | cut -d' ' -f1 | sort > .assets-id
      - restore_cache:
          keys:
            - v1-lfscache-{{ checksum ".assets-id" }}
            - v1-lfscache-
      - run: git lfs pull
      - save_cache:
          paths:
            - .git/lfs
          key: v1-lfscache-{{ checksum ".assets-id" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn status
      - run: yarn build
      - run: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: release